// Code generated by protoc-gen-go. DO NOT EDIT.
// source: s2s.proto

package s2s

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// client  <-> server  10000 - 19999
type MessageCmd int32

const (
	MessageCmd_NULL       MessageCmd = 0
	MessageCmd_GetUID     MessageCmd = 1
	MessageCmd_GetUIDs    MessageCmd = 2
	MessageCmd_ValidToken MessageCmd = 3
	MessageCmd_GetUser    MessageCmd = 4
	MessageCmd_GetWallet  MessageCmd = 5
)

var MessageCmd_name = map[int32]string{
	0: "NULL",
	1: "GetUID",
	2: "GetUIDs",
	3: "ValidToken",
	4: "GetUser",
	5: "GetWallet",
}

var MessageCmd_value = map[string]int32{
	"NULL":       0,
	"GetUID":     1,
	"GetUIDs":    2,
	"ValidToken": 3,
	"GetUser":    4,
	"GetWallet":  5,
}

func (x MessageCmd) String() string {
	return proto.EnumName(MessageCmd_name, int32(x))
}

func (MessageCmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{0}
}

type ErrorCode int32

const (
	ErrorCode_OK ErrorCode = 0
)

var ErrorCode_name = map[int32]string{
	0: "OK",
}

var ErrorCode_value = map[string]int32{
	"OK": 0,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{1}
}

type Result struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{0}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//snowflake proto
type GenUIDReq struct {
	Channel              int32    `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenUIDReq) Reset()         { *m = GenUIDReq{} }
func (m *GenUIDReq) String() string { return proto.CompactTextString(m) }
func (*GenUIDReq) ProtoMessage()    {}
func (*GenUIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{1}
}

func (m *GenUIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenUIDReq.Unmarshal(m, b)
}
func (m *GenUIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenUIDReq.Marshal(b, m, deterministic)
}
func (m *GenUIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenUIDReq.Merge(m, src)
}
func (m *GenUIDReq) XXX_Size() int {
	return xxx_messageInfo_GenUIDReq.Size(m)
}
func (m *GenUIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GenUIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_GenUIDReq proto.InternalMessageInfo

func (m *GenUIDReq) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

type GenUIDResp struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenUIDResp) Reset()         { *m = GenUIDResp{} }
func (m *GenUIDResp) String() string { return proto.CompactTextString(m) }
func (*GenUIDResp) ProtoMessage()    {}
func (*GenUIDResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{2}
}

func (m *GenUIDResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenUIDResp.Unmarshal(m, b)
}
func (m *GenUIDResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenUIDResp.Marshal(b, m, deterministic)
}
func (m *GenUIDResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenUIDResp.Merge(m, src)
}
func (m *GenUIDResp) XXX_Size() int {
	return xxx_messageInfo_GenUIDResp.Size(m)
}
func (m *GenUIDResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GenUIDResp.DiscardUnknown(m)
}

var xxx_messageInfo_GenUIDResp proto.InternalMessageInfo

func (m *GenUIDResp) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GenUIDResp) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GenUIDsReq struct {
	Channel              int32    `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Num                  int32    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenUIDsReq) Reset()         { *m = GenUIDsReq{} }
func (m *GenUIDsReq) String() string { return proto.CompactTextString(m) }
func (*GenUIDsReq) ProtoMessage()    {}
func (*GenUIDsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{3}
}

func (m *GenUIDsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenUIDsReq.Unmarshal(m, b)
}
func (m *GenUIDsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenUIDsReq.Marshal(b, m, deterministic)
}
func (m *GenUIDsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenUIDsReq.Merge(m, src)
}
func (m *GenUIDsReq) XXX_Size() int {
	return xxx_messageInfo_GenUIDsReq.Size(m)
}
func (m *GenUIDsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GenUIDsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GenUIDsReq proto.InternalMessageInfo

func (m *GenUIDsReq) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *GenUIDsReq) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type GenUIDsResp struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Uids                 []uint64 `protobuf:"varint,2,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenUIDsResp) Reset()         { *m = GenUIDsResp{} }
func (m *GenUIDsResp) String() string { return proto.CompactTextString(m) }
func (*GenUIDsResp) ProtoMessage()    {}
func (*GenUIDsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{4}
}

func (m *GenUIDsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenUIDsResp.Unmarshal(m, b)
}
func (m *GenUIDsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenUIDsResp.Marshal(b, m, deterministic)
}
func (m *GenUIDsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenUIDsResp.Merge(m, src)
}
func (m *GenUIDsResp) XXX_Size() int {
	return xxx_messageInfo_GenUIDsResp.Size(m)
}
func (m *GenUIDsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GenUIDsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GenUIDsResp proto.InternalMessageInfo

func (m *GenUIDsResp) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GenUIDsResp) GetUids() []uint64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

type ValidTokenReq struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidTokenReq) Reset()         { *m = ValidTokenReq{} }
func (m *ValidTokenReq) String() string { return proto.CompactTextString(m) }
func (*ValidTokenReq) ProtoMessage()    {}
func (*ValidTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{5}
}

func (m *ValidTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidTokenReq.Unmarshal(m, b)
}
func (m *ValidTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidTokenReq.Marshal(b, m, deterministic)
}
func (m *ValidTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidTokenReq.Merge(m, src)
}
func (m *ValidTokenReq) XXX_Size() int {
	return xxx_messageInfo_ValidTokenReq.Size(m)
}
func (m *ValidTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_ValidTokenReq proto.InternalMessageInfo

func (m *ValidTokenReq) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *ValidTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidTokenResp struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidTokenResp) Reset()         { *m = ValidTokenResp{} }
func (m *ValidTokenResp) String() string { return proto.CompactTextString(m) }
func (*ValidTokenResp) ProtoMessage()    {}
func (*ValidTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{6}
}

func (m *ValidTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidTokenResp.Unmarshal(m, b)
}
func (m *ValidTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidTokenResp.Marshal(b, m, deterministic)
}
func (m *ValidTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidTokenResp.Merge(m, src)
}
func (m *ValidTokenResp) XXX_Size() int {
	return xxx_messageInfo_ValidTokenResp.Size(m)
}
func (m *ValidTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_ValidTokenResp proto.InternalMessageInfo

func (m *ValidTokenResp) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type User struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Appid                string   `protobuf:"bytes,2,opt,name=appid,proto3" json:"appid,omitempty"`
	Openid               string   `protobuf:"bytes,3,opt,name=openid,proto3" json:"openid,omitempty"`
	Uuid                 string   `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Channel              string   `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"`
	Avatar               string   `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Password             string   `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	Gender               int32    `protobuf:"varint,10,opt,name=gender,proto3" json:"gender,omitempty"`
	Age                  int32    `protobuf:"varint,11,opt,name=age,proto3" json:"age,omitempty"`
	Gold                 uint64   `protobuf:"varint,12,opt,name=gold,proto3" json:"gold,omitempty"`
	Coin                 uint64   `protobuf:"varint,13,opt,name=coin,proto3" json:"coin,omitempty"`
	LoginAt              string   `protobuf:"bytes,14,opt,name=loginAt,proto3" json:"loginAt,omitempty"`
	LoginIP              string   `protobuf:"bytes,15,opt,name=loginIP,proto3" json:"loginIP,omitempty"`
	CreateAt             string   `protobuf:"bytes,16,opt,name=createAt,proto3" json:"createAt,omitempty"`
	Status               int32    `protobuf:"varint,17,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{7}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *User) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *User) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *User) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetGold() uint64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *User) GetCoin() uint64 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *User) GetLoginAt() string {
	if m != nil {
		return m.LoginAt
	}
	return ""
}

func (m *User) GetLoginIP() string {
	if m != nil {
		return m.LoginIP
	}
	return ""
}

func (m *User) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *User) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type GetUserReq struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserReq) Reset()         { *m = GetUserReq{} }
func (m *GetUserReq) String() string { return proto.CompactTextString(m) }
func (*GetUserReq) ProtoMessage()    {}
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{8}
}

func (m *GetUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReq.Unmarshal(m, b)
}
func (m *GetUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReq.Marshal(b, m, deterministic)
}
func (m *GetUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReq.Merge(m, src)
}
func (m *GetUserReq) XXX_Size() int {
	return xxx_messageInfo_GetUserReq.Size(m)
}
func (m *GetUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReq proto.InternalMessageInfo

func (m *GetUserReq) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetUserResp struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResp) Reset()         { *m = GetUserResp{} }
func (m *GetUserResp) String() string { return proto.CompactTextString(m) }
func (*GetUserResp) ProtoMessage()    {}
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{9}
}

func (m *GetUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResp.Unmarshal(m, b)
}
func (m *GetUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResp.Marshal(b, m, deterministic)
}
func (m *GetUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResp.Merge(m, src)
}
func (m *GetUserResp) XXX_Size() int {
	return xxx_messageInfo_GetUserResp.Size(m)
}
func (m *GetUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResp proto.InternalMessageInfo

func (m *GetUserResp) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetUserResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetWalletReq struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletReq) Reset()         { *m = GetWalletReq{} }
func (m *GetWalletReq) String() string { return proto.CompactTextString(m) }
func (*GetWalletReq) ProtoMessage()    {}
func (*GetWalletReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{10}
}

func (m *GetWalletReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletReq.Unmarshal(m, b)
}
func (m *GetWalletReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletReq.Marshal(b, m, deterministic)
}
func (m *GetWalletReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletReq.Merge(m, src)
}
func (m *GetWalletReq) XXX_Size() int {
	return xxx_messageInfo_GetWalletReq.Size(m)
}
func (m *GetWalletReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletReq proto.InternalMessageInfo

func (m *GetWalletReq) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetWalletResp struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Gold                 uint64   `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`
	Coin                 uint64   `protobuf:"varint,4,opt,name=coin,proto3" json:"coin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletResp) Reset()         { *m = GetWalletResp{} }
func (m *GetWalletResp) String() string { return proto.CompactTextString(m) }
func (*GetWalletResp) ProtoMessage()    {}
func (*GetWalletResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{11}
}

func (m *GetWalletResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletResp.Unmarshal(m, b)
}
func (m *GetWalletResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletResp.Marshal(b, m, deterministic)
}
func (m *GetWalletResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletResp.Merge(m, src)
}
func (m *GetWalletResp) XXX_Size() int {
	return xxx_messageInfo_GetWalletResp.Size(m)
}
func (m *GetWalletResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletResp proto.InternalMessageInfo

func (m *GetWalletResp) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetWalletResp) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetWalletResp) GetGold() uint64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *GetWalletResp) GetCoin() uint64 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func init() {
	proto.RegisterEnum("s2s.MessageCmd", MessageCmd_name, MessageCmd_value)
	proto.RegisterEnum("s2s.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*Result)(nil), "s2s.Result")
	proto.RegisterType((*GenUIDReq)(nil), "s2s.GenUIDReq")
	proto.RegisterType((*GenUIDResp)(nil), "s2s.GenUIDResp")
	proto.RegisterType((*GenUIDsReq)(nil), "s2s.GenUIDsReq")
	proto.RegisterType((*GenUIDsResp)(nil), "s2s.GenUIDsResp")
	proto.RegisterType((*ValidTokenReq)(nil), "s2s.ValidTokenReq")
	proto.RegisterType((*ValidTokenResp)(nil), "s2s.ValidTokenResp")
	proto.RegisterType((*User)(nil), "s2s.User")
	proto.RegisterType((*GetUserReq)(nil), "s2s.GetUserReq")
	proto.RegisterType((*GetUserResp)(nil), "s2s.GetUserResp")
	proto.RegisterType((*GetWalletReq)(nil), "s2s.GetWalletReq")
	proto.RegisterType((*GetWalletResp)(nil), "s2s.GetWalletResp")
}

func init() { proto.RegisterFile("s2s.proto", fileDescriptor_953aa047daafed82) }

var fileDescriptor_953aa047daafed82 = []byte{
	// 560 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x8b, 0xd3, 0x4c,
	0x14, 0xde, 0x36, 0x1f, 0xdd, 0x9c, 0x6c, 0xfb, 0xe6, 0x1d, 0x65, 0x19, 0x04, 0xa5, 0x8c, 0x08,
	0x65, 0x2f, 0x7a, 0x51, 0x11, 0x84, 0xbd, 0x5a, 0xbb, 0xba, 0x14, 0x57, 0x5d, 0x83, 0x55, 0xd0,
	0xab, 0xb1, 0x19, 0xb2, 0xc1, 0x74, 0x12, 0x67, 0x26, 0xfa, 0x27, 0xfc, 0xd1, 0x72, 0x66, 0x92,
	0xb4, 0xe0, 0x22, 0xc5, 0xbb, 0xe7, 0x39, 0x9f, 0xcf, 0x9c, 0x73, 0x12, 0x88, 0xf4, 0x42, 0xcf,
	0x6b, 0x55, 0x99, 0x8a, 0x78, 0x7a, 0xa1, 0xd9, 0x1c, 0xc2, 0x54, 0xe8, 0xa6, 0x34, 0x84, 0x80,
	0xbf, 0xa9, 0x32, 0x41, 0x07, 0xd3, 0xc1, 0x2c, 0x48, 0x2d, 0x26, 0x09, 0x78, 0x5b, 0x9d, 0xd3,
	0xe1, 0x74, 0x30, 0x8b, 0x52, 0x84, 0xec, 0x09, 0x44, 0x57, 0x42, 0xae, 0x57, 0x97, 0xa9, 0xf8,
	0x4e, 0x28, 0x8c, 0x36, 0xb7, 0x5c, 0x4a, 0x51, 0xb6, 0x59, 0x1d, 0x65, 0x4b, 0x80, 0x2e, 0x4c,
	0xd7, 0xe4, 0x31, 0x84, 0xca, 0x36, 0xb1, 0x61, 0xf1, 0x22, 0x9e, 0xa3, 0x0a, 0xd7, 0x37, 0x6d,
	0x5d, 0xd8, 0xab, 0x29, 0x32, 0xdb, 0xcb, 0x4f, 0x11, 0xb2, 0xe7, 0x5d, 0x11, 0xfd, 0xd7, 0x66,
	0x98, 0x29, 0x9b, 0xad, 0xcd, 0x0c, 0x52, 0x84, 0xec, 0x15, 0xc4, 0x7d, 0xe6, 0xa1, 0xfd, 0x09,
	0xf8, 0x4d, 0x91, 0x69, 0x3a, 0x9c, 0x7a, 0x33, 0x3f, 0xb5, 0x98, 0x9d, 0xc3, 0xf8, 0x23, 0x2f,
	0x8b, 0xec, 0x43, 0xf5, 0x4d, 0x48, 0x14, 0x71, 0x1f, 0x02, 0x5e, 0xd7, 0x45, 0x66, 0x0b, 0x45,
	0xa9, 0x23, 0x68, 0x35, 0x18, 0xd1, 0x0e, 0xca, 0x11, 0xf6, 0x0c, 0x26, 0xfb, 0xc9, 0x07, 0xea,
	0x60, 0xbf, 0x3c, 0xf0, 0xd7, 0x5a, 0xa8, 0x6e, 0x20, 0x83, 0x7e, 0x20, 0xbb, 0xee, 0xc3, 0xfd,
	0xee, 0xa7, 0x10, 0x56, 0xb5, 0x90, 0x45, 0x46, 0x3d, 0x6b, 0x6e, 0x99, 0x7d, 0x10, 0x16, 0xf0,
	0xad, 0xd5, 0x62, 0xb4, 0x49, 0xbe, 0x15, 0x34, 0x70, 0x36, 0xc4, 0xfb, 0x83, 0x0d, 0xad, 0xb9,
	0x1f, 0xec, 0x29, 0x84, 0xfc, 0x07, 0x37, 0x5c, 0xd1, 0x91, 0xab, 0xec, 0x18, 0x79, 0x00, 0xc7,
	0x35, 0xd7, 0xfa, 0x67, 0xa5, 0x32, 0x7a, 0x6c, 0x3d, 0x3d, 0x47, 0x8d, 0xf5, 0x6d, 0x25, 0x05,
	0x8d, 0x9c, 0x46, 0x4b, 0xb0, 0x52, 0x2e, 0x64, 0x26, 0x14, 0x05, 0xbb, 0xa5, 0x96, 0xe1, 0x1b,
	0x79, 0x2e, 0x68, 0xec, 0x56, 0xc7, 0x73, 0x81, 0x0a, 0xf3, 0xaa, 0xcc, 0xe8, 0x89, 0x7d, 0xb6,
	0xc5, 0xee, 0x34, 0x0b, 0x49, 0xc7, 0xce, 0x86, 0x18, 0x55, 0x97, 0x55, 0x5e, 0xc8, 0x0b, 0x43,
	0x27, 0x4e, 0x75, 0x4b, 0x7b, 0xcf, 0xea, 0x86, 0xfe, 0xb7, 0xe7, 0x59, 0xdd, 0xa0, 0xee, 0x8d,
	0x12, 0xdc, 0x88, 0x0b, 0x43, 0x13, 0xa7, 0xbb, 0xe3, 0xa8, 0x50, 0x1b, 0x6e, 0x1a, 0x4d, 0xff,
	0x77, 0x0a, 0x1d, 0x63, 0x8f, 0xf0, 0x08, 0x0d, 0x2e, 0x04, 0xf7, 0xff, 0xc7, 0x4e, 0xd8, 0x7b,
	0x3c, 0xb5, 0xd6, 0x7f, 0xe8, 0xa9, 0x3d, 0x04, 0xbf, 0xd1, 0x42, 0xd9, 0x35, 0xc6, 0x8b, 0xc8,
	0x86, 0xd8, 0x0a, 0xd6, 0xcc, 0xa6, 0x70, 0x72, 0x25, 0xcc, 0x27, 0x5e, 0x96, 0xc2, 0xdc, 0xdd,
	0x54, 0xc2, 0x78, 0x2f, 0xe2, 0x9f, 0xbf, 0xb0, 0x7e, 0xd8, 0xde, 0x1d, 0xc3, 0xf6, 0x77, 0xc3,
	0x3e, 0xfb, 0x02, 0xf0, 0x46, 0x68, 0xcd, 0x73, 0xb1, 0xdc, 0x66, 0xe4, 0x18, 0xfc, 0xb7, 0xeb,
	0xeb, 0xeb, 0xe4, 0x88, 0x00, 0x84, 0xf8, 0xf8, 0xd5, 0x65, 0x32, 0x20, 0x31, 0x8c, 0x1c, 0xd6,
	0xc9, 0x90, 0x4c, 0x00, 0x76, 0xb7, 0x9f, 0x78, 0x9d, 0x53, 0x0b, 0x95, 0xf8, 0x64, 0x8c, 0xff,
	0x90, 0x56, 0x7d, 0x12, 0x9c, 0xdd, 0x83, 0xe8, 0xa5, 0x52, 0x95, 0x5a, 0xe2, 0x1f, 0x27, 0x84,
	0xe1, 0xbb, 0xd7, 0xc9, 0xd1, 0x8b, 0xd1, 0xe7, 0x60, 0x7e, 0xae, 0x17, 0xfa, 0x6b, 0x68, 0x7f,
	0x56, 0x4f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x35, 0xc9, 0xc3, 0xb9, 0x04, 0x00, 0x00,
}
